global using Autodesk.AutoCAD;
global using Autodesk.AutoCAD.ApplicationServices;
global using Autodesk.AutoCAD.Colors;
global using Autodesk.AutoCAD.DatabaseServices;
global using Autodesk.AutoCAD.DatabaseServices.Filters;
global using Autodesk.AutoCAD.EditorInput;
global using Autodesk.AutoCAD.Geometry;
global using Autodesk.AutoCAD.GraphicsInterface;
global using Autodesk.AutoCAD.Runtime;
global using IFoxCAD.Basal;
global using IFoxCAD.Cad;
global using Microsoft.CSharp.RuntimeBinder;
global using Microsoft.Win32;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Collections.Specialized;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Drawing;
global using System.IO;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Web.Script.Serialization;
global using System.Windows.Forms;
global using Acap = Autodesk.AutoCAD.ApplicationServices.Application;
global using Acaop = Autodesk.AutoCAD.ApplicationServices.Core.Application;
global using Color = Autodesk.AutoCAD.Colors.Color;
global using Cad_DwgFiler = Autodesk.AutoCAD.DatabaseServices.DwgFiler;
global using Cad_DxfFiler = Autodesk.AutoCAD.DatabaseServices.DxfFiler;
global using Group = Autodesk.AutoCAD.DatabaseServices.Group;
global using Polyline = Autodesk.AutoCAD.DatabaseServices.Polyline;
global using Viewport = Autodesk.AutoCAD.DatabaseServices.Viewport;
global using Acgi = Autodesk.AutoCAD.GraphicsInterface;
global using WorldDraw = Autodesk.AutoCAD.GraphicsInterface.WorldDraw;
global using Manager = Autodesk.AutoCAD.GraphicsSystem.Manager;
global using Cad_ErrorStatus = Autodesk.AutoCAD.Runtime.ErrorStatus;
global using AcException = Autodesk.AutoCAD.Runtime.Exception;
global using Registry = Microsoft.Win32.Registry;
global using RegistryKey = Microsoft.Win32.RegistryKey;
global using Exception = System.Exception;

